apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: fluentd-agent
    meta.helm.sh/release-namespace: agent
  generation: 1
  labels:
    app.kubernetes.io/instance: fluentd-agent
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/version: v1.12.4
    helm.sh/chart: fluentd-0.3.5
  name: fluentd-agent
  namespace: agent
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: fluentd-agent
      app.kubernetes.io/name: fluentd
  template:
    metadata:
      annotations:
        checksum/config: 067254dfa9ef10cb1ec3bd6159b8e5ed89dc150f8a84289a358676901b551ea0
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: fluentd-agent
        app.kubernetes.io/name: fluentd
    spec:
      containers:
      - env:
        - name: FLUENTD_CONF
          value: ../../../etc/fluent/fluent.conf
        - name: FLUENT_FOWARD_HOST
          value: fluentd-dep.logging.svc.cluster.local
        - name: FLUENT_FOWARD_PORT
          value: "18080"
        image: fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-elasticsearch7-1.0
        imagePullPolicy: IfNotPresent
        name: fluentd
        ports:
        - containerPort: 24231
          name: metrics
          protocol: TCP
        - containerPort: 24224
          name: forwarder
          protocol: TCP
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/fluent
          name: etcfluentd-main
        - mountPath: /etc/fluent/config.d/
          name: etcfluentd-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluentd-agent
      serviceAccountName: fluentd-agent
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
      - configMap:
          defaultMode: 511
          name: fluentd-main
        name: etcfluentd-main
      - configMap:
          defaultMode: 511
          name: fluentd-config
        name: etcfluentd-config
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

