apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: fluentd-dep
    meta.helm.sh/release-namespace: logging
  labels:
    app.kubernetes.io/instance: fluentd-dep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/version: v1.12.4
    helm.sh/chart: fluentd-0.3.5
  name: fluentd-dep
  namespace: logging
spec:
  clusterIP: 10.97.168.212
  clusterIPs:
  - 10.97.168.212
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: metrics
    port: 24231
    protocol: TCP
    targetPort: metrics
  - name: forwarder
    port: 24224
    protocol: TCP
    targetPort: 24224
  selector:
    app.kubernetes.io/instance: fluentd-dep
    app.kubernetes.io/name: fluentd
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
