apiVersion: v1
data:
  01_sources.conf: |-
    ## capture logs from agent
    <source>
      @type forward
      port 24224
      tag aggr.log
    </source>

    <filter aggr.**>
      @type record_transformer
      enable_ruby true
      <record>
        namespace_pod_name ${record["kubernetes"]["namespace_name"]}.${record["kubernetes"]["pod_name"]}
      </record>
    </filter>   

    <match aggr.**>
      @type rewrite_tag_filter
      <rule> 
        key $.namespace_pod_name
        pattern ^(.+)$ 
        tag $1
      </rule>
    </match>

    <filter **etcd-** **elastic** **kibana** **calico-**>
      @type record_transformer
      remove_keys $.namespace_pod_name
    </filter>

    # parse JSON logs from etcd, elastic and kibana pods
    <filter **etcd-** **elastic** **kibana**>
      @type parser
      reserve_data true
      key_name "$.message"
      suppress_parse_error_log true      
      <parse>
        @type json
      </parse>
    </filter>

    # Parse Non-JSON logs for calico pods in the kube-system namespace
    <filter **calico-**>
      @type parser
      key_name "$.message"
      reserve_data true
      suppress_parse_error_log true
      <parse>
        @type regexp
        expression ^(?<ts>[^ ]* [^ ]*)\s+\[(?<SEV>\w+)\]\[\d+\]\s+(?<Go-Module>[^ ]*)(?<message>.*)$
      </parse>
    </filter>  
    
  04_outputs.conf: |-
      <match **>
        @type elasticsearch
        host "elasticsearch.elastic-kibana"
        port 9200
        path ""
        user elastic
        password changeme
        index_name fluentd-k8s
      </match>

kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fluentd-dep
    meta.helm.sh/release-namespace: logging
  labels:
    app.kubernetes.io/instance: fluentd-dep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/version: v1.12.4
    helm.sh/chart: fluentd-0.3.5
  name: fluentd-config
  namespace: logging
