apiVersion: v1
data:
  01_sources.conf: |-
    ## capture logs from agent
    <source>
      @type forward
      port 24224
      allapps.log
    </source>

    <filter allapps**>
      @type record_transformer
      enable_ruby true
      <record>
        namespace_pod_name ${record["kubernetes"]["namespace_name"]}.${record["kubernetes"]["pod_name"]}
      </record>
    </filter>   

    <match allapps**>
      @type rewrite_tag_filter
      <rule> 
        key $.namespace_pod_name
        pattern ^(.+)$ 
        tag $1
      </rule>
    </match>

    <filter elastic-kibana** app1**>
      @type record_transformer
      remove_keys $.namespace_pod_name
    </filter>

    # parse JSON logs from elastic-kibana namespace
    <filter elastic-kibana**>
      @type parser
      reserve_data true
      key_name "$.message"    
      <parse>
        @type json
      </parse>
    </filter>

    # parse logs from app1 namespace
    <filter app1**>
      @type parser
      reserve_data true
      key_name "$.message"    
      <parse>
        @type apache2
      </parse>
    </filter>

    <match bookinfo.productpage**>
      @type file
      path /var/log/fluent/productpage.${tag}.%Y%m%d
      compress gzip
      <buffer>
        timekey 3600
        timekey_use_utc true
        timekey_wait 10m
     </buffer>
    </match>

    <source>
      @type tail
      @id productpage_logs
      path /var/log/fluent/productpage*.log
      pos_file /var/log/fluentd-productpage.log.pos
      multiline_flush_interval 5s
      tag bookinfo.productpage**
      read_from_head true
      <parse>
        @type multiline
        format_firstline /^send:/
        format1 /^(?<send>.*)$\n/
        format2 /^(?<reply>.*)$\n/
        format3 /^(?<header1>.*)$\n/
        format4 /^(?<header2>.*)$\n/
        format5 /^(?<header3>.*)$\n/
        format6 /^(?<header4>.*)$\n/
        format7 /^(?<header5>.*)$\n/
        format8 /\w+(?=:)\n/
        format9 /\w+(?=:)/			
      </parse>    
    </source>

  04_outputs.conf: |-
      <match **>
        @type elasticsearch
        host "elasticsearch.elastic-kibana"
        port 9200
        path ""
        user elastic
        password changeme
        index_name fluentd-k8s
      </match>

kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fluentd-dep
    meta.helm.sh/release-namespace: logging
  labels:
    app.kubernetes.io/instance: fluentd-dep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/version: v1.12.4
    helm.sh/chart: fluentd-0.3.5
  name: fluentd-config
  namespace: logging
