apiVersion: v1
data:
  fluent.conf: |-
    # do not collect fluentd logs to avoid infinite loops.
    <label @FLUENT_LOG>
      <match **>
        @type null
        @id ignore_fluent_logs
      </match>
    </label>

    @include config.d/*.conf

kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fluentd-dep
    meta.helm.sh/release-namespace: logging
  labels:
    app.kubernetes.io/instance: fluentd-dep
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/version: v1.12.4
    helm.sh/chart: fluentd-0.3.5
  name: fluentd-main
  namespace: logging

