apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 185fae3b96af7c900fa87a05ae616bc0a2bcedeec1648f9dc190f45e6ae5a015
    cni.projectcalico.org/containerID: 5d4209147850c374c9092105a06868dc981d4f6a554b7ac5152a244bc00fab9b
    cni.projectcalico.org/podIP: 192.168.111.39/32
    cni.projectcalico.org/podIPs: 192.168.111.39/32
  creationTimestamp: "2022-02-02T13:10:41Z"
  generateName: fluentd-dep-66c558789b-
  labels:
    app.kubernetes.io/instance: fluentd-dep
    app.kubernetes.io/name: fluentd
    pod-template-hash: 66c558789b
  name: fluentd-dep-66c558789b-rtw6g
  namespace: logging
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: fluentd-dep-66c558789b
    uid: c1bca103-1e24-48ec-8b5f-79f28358746f
  resourceVersion: "1159690"
  uid: 06930eaf-de3d-4be5-885b-fc14bc2ad640
spec:
  containers:
  - env:
    - name: FLUENTD_CONF
      value: ../../../etc/fluent/fluent.conf
    - name: FLUENT_ELASTICSEARCH_HOST
      value: elasticsearch.elastic-kibana
    - name: FLUENT_ELASTICSEARCH_PORT
      value: "9200"
    image: fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-elasticsearch7-1.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: metrics
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: fluentd
    ports:
    - containerPort: 24231
      name: metrics
      protocol: TCP
    - containerPort: 24224
      name: forwarder
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /metrics
        port: metrics
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/docker/containers
      name: varlibdockercontainers
      readOnly: true
    - mountPath: /etc/fluent
      name: etcfluentd-main
    - mountPath: /etc/fluent/config.d/
      name: etcfluentd-config
    - mountPath: /etc/fluent/fluentd-prometheus-conf.d
      name: fluentd-custom-cm-fluentd-prometheus-conf
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5qtvw
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: 8ab4e5a06d1c.mylabserver.com
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fluentd-dep
  serviceAccountName: fluentd-dep
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /var/log
      type: ""
    name: varlog
  - hostPath:
      path: /var/lib/docker/containers
      type: ""
    name: varlibdockercontainers
  - configMap:
      defaultMode: 511
      name: fluentd-main
    name: etcfluentd-main
  - configMap:
      defaultMode: 511
      name: fluentd-config
    name: etcfluentd-config
  - configMap:
      defaultMode: 511
      name: fluentd-prometheus-conf
    name: fluentd-custom-cm-fluentd-prometheus-conf
  - name: kube-api-access-5qtvw
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-02T13:10:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-02T13:10:51Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-02T13:10:51Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-02T13:10:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://084df0e28ab4c508642f2704149fa2acf56e334a02031ec51950a51fe7a032c0
    image: docker.io/fluent/fluentd-kubernetes-daemonset:v1.12.4-debian-elasticsearch7-1.0
    imageID: docker.io/fluent/fluentd-kubernetes-daemonset@sha256:656423b5fabbeb64c27e7410efa98da0ee6ec503871c480e1d2ae57cd470a38c
    lastState: {}
    name: fluentd
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-02-02T13:10:42Z"
  hostIP: 172.31.36.228
  phase: Running
  podIP: 192.168.111.39
  podIPs:
  - ip: 192.168.111.39
  qosClass: BestEffort
  startTime: "2022-02-02T13:10:41Z"
